# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-22 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommentTbl',
            fields=[
                ('CommentsId', models.IntegerField(primary_key=True, serialize=False)),
                ('Comments', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='ComparisonTbl',
            fields=[
                ('ComparisonId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ItemTbl',
            fields=[
                ('ItemId', models.IntegerField(primary_key=True, serialize=False)),
                ('ItemName', models.CharField(max_length=255)),
                ('ItemDescription', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserTbl',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=255)),
                ('UserEmail', models.CharField(max_length=255)),
                ('UserDescription', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='comparisontbl',
            name='FirstItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firstitem', to='mycomparison.ItemTbl'),
        ),
        migrations.AddField(
            model_name='comparisontbl',
            name='SecondItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seconditem', to='mycomparison.ItemTbl'),
        ),
        migrations.AddField(
            model_name='commenttbl',
            name='ComparisonId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycomparison.ComparisonTbl'),
        ),
        migrations.AddField(
            model_name='commenttbl',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mycomparison.UserTbl'),
        ),
    ]
