# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-31 01:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomparison', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparisontbl',
            name='Vote1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comparisontbl',
            name='Vote2',
            field=models.IntegerField(default=0),
        ),
    ]
